# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-18.04

steps:
  - task: Maven@3
    displayName: 'Maven pom.xml'
    options: '-DskipITs --settings ./maven/settings.xml'
  - task: CopyFiles@2
    displayName: 'Copy Files'
    inputs:
     Contents: | 
      **/target/*.war
      *.sql
     TargetFolder: '$(build.artifactstagingdirectory)'
 
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact'
    inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'